
networks:
  bot:
    external: false

services:

  bot-backend:
    container_name: bot-backend
    build:
      context: ./Telegram-Bot-Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bot
    expose:
      - "8000"
    env_file:
      - ./Telegram-Bot-Backend/.env
    command: uvicorn bot_backend.backend_api:app --host 0.0.0.0 --port 8000

  bot:
    container_name: bot
    build:
      context: ./Telegram-Bot
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bot
    depends_on:
      - bot-backend
    env_file:
       - ./Telegram-Bot/.env
    command: python bot/main.py