
networks:
  bot:
    external: false

services:

  # db:
  #   image: postgres
  #   volumes:
  #     postgres_data:/var/lib/postgresql/data
  #   env_file: 

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bot
    expose:
      - "8000"
    env_file:
      - ./Backend/.env
    command: uvicorn backend.backend_api:app --host 0.0.0.0 --port 8000

  bot:
    container_name: bot
    build:
      context: ./Bot
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bot
    depends_on:
      - backend
    env_file:
       - ./Bot/.env
    command: python bot/main.py

# volumes:
#   postgres_data: