name: CI

on:
  push:
  pull_request:

jobs:
  run-unit-test:
    strategy:
      fail-fast: false

    name: Test
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@5.6.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install pytest-asyncio
          python -m pip install pytest_asyncio
          python -m pip install aiogram
          python -m pip install requests

      - name: Run tests
        run: pytest
